name: todoey
description: To-Do List App
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  flutter_slidable: ^0.5.7

  flutter_spinkit: ^5.0.0
  animated_splash_screen: ^1.0.1+2
  page_transition: ^1.1.7+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

